---
kind: pkgfile.Build
spec:
  targets:
    - overlays
  makefile:
    extraVariables:
      - name: OVERLAYS_IMAGE_REF
        defaultValue: $(REGISTRY_AND_USERNAME)/overlays:$(TAG)
---
kind: common.Build
spec:
    ignoredPaths:
        - "internal/overlays/overlays-generated.yaml"
---
kind: auto.CustomSteps
spec:
  steps:
    - name: internal/overlays/overlays-generated.yaml
      toplevel: true
    - name: overlays
      toplevel: true
    - name: $(ARTIFACTS)/image-signer
      toplevel: true
    - name: sign-images
      toplevel: true
---
kind: custom.Step
name: internal/overlays/overlays-generated.yaml
spec:
  makefile:
    enabled: true
    phony: true
    script:
      - "@./hack/scripts/generate-digests.sh"
---
kind: custom.Step
name: overlays
spec:
  makefile:
    enabled: true
    phony: true
    depends:
      - internal/overlays/overlays-generated.yaml
---
kind: custom.Step
name: $(ARTIFACTS)/image-signer
spec:
  makefile:
    enabled: true
    phony: true
    variables:
      - name: IMAGE_SIGNER_RELEASE
        defaultValue: v0.1.1
    script:
      - |
        @curl -sSL https://github.com/siderolabs/go-tools/releases/download/$(IMAGE_SIGNER_RELEASE)/image-signer-$(OPERATING_SYSTEM)-$(GOARCH) -o $(ARTIFACTS)/image-signer
        @chmod +x $(ARTIFACTS)/image-signer
---
kind: custom.Step
name: sign-images
spec:
  makefile:
    enabled: true
    phony: true
    depends:
      - $(ARTIFACTS)/image-signer
    script:
      - |
        @$(ARTIFACTS)/image-signer sign \
          $(shell crane export $(OVERLAYS_IMAGE_REF) | tar x --to-stdout overlays.yaml | yq '.overlays | unique_by(.image) | .[] | .image + "@" + .digest') \
          $(OVERLAYS_IMAGE_REF)@$$(crane digest $(OVERLAYS_IMAGE_REF))
